# Generated by Django 3.2.16 on 2023-01-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='recipe_app.RecipeIngredient', to='recipe_app.Ingredient'),
        ),
    ]
