# Generated by Django 3.2.16 on 2023-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
