# Generated by Django 4.1.7 on 2024-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_tag_alter_ingredient_name_alter_recipe_directions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipe_app.tag'),
        ),
    ]
